/**
 * P1 English chrome. CCO authors every Myanmar string later (F50).
 * Job titles stay English. Server mmReady / contentMm is CCO data, not chrome.
 * Zero emoji. Formal register when MM lands.
 */
export const copy = {
  appName: "ReferTRM",
  tagline: "Myanmar career platform",

  nav: {
    home: "Home",
    jobs: "Jobs",
    learn: "Learn",
    academy: "Learn",
    earn: "Earn",
    me: "Me",
  },

  start: {
    title: "Start",
    subtitle: "Choose a path",
    startHere: "Start here",
    jobs: "Jobs",
    academy: "Academy",
    careerGame: "Career Game",
    overflow: "Full Start on the web",
  },

  jobs: {
    title: "Jobs",
    search: "Search jobs",
    filterAll: "All",
    yangon: "Yangon",
    mandalay: "Mandalay",
    remote: "Remote",
    urgent: "Urgent",
    empty: "No jobs match your search.",
    emptyOffline: "No saved jobs yet. Connect once to download the list.",
    count: (n: number) => `${n} open roles`,
    locationUnknown: "Location not listed",
    salaryHidden: "Salary not listed",
    descriptionOffline: "Job description needs a connection.",
    descriptionEmpty: "No description listed.",
    requirementsOffline: "Requirements need a connection.",
    requirementsEmpty: "No requirements listed.",
    inactive: "This job is no longer listed as open.",
    requirements: "Requirements",
    aboutRole: "About this role",
    description: "Description",
    refresh: "Try again",
    fullTime: "Full time",
    partTime: "Part time",
    contract: "Contract",
    internship: "Internship",
  },

  academy: {
    title: "Academy",
    empty: "No published courses match your search.",
    emptyOffline: "No saved courses yet. Connect once to download the catalogue.",
    minutes: (n: number) => `${n} min`,
    xp: (n: number) => `${n} XP`,
    count: (n: number) => `${n} published courses`,
    search: "Search courses",
    bodyOffline: "This lesson needs a connection the first time.",
    languageEn: "English",
    languageMm: "Myanmar",
    myanmarAvailable: "Myanmar available",
    allTopics: "All topics",
    questions: "Questions",
    mmHidden: "Myanmar for this lesson is not approved yet. English is shown instead.",
    furtherReading: "Further reading",
    whatYouLearn: "What you will learn",
    keyTakeaway: "Key takeaway",
    commonMistake: "Common mistake",
    actionSteps: "Action steps",
    decisionScenario: "Decision scenario",
    vocabulary: "Key terms",
    quizTitle: "Practice quiz",
    quizProgress: (index: number, total: number) => `Question ${index} of ${total}`,
    quizCorrect: "Correct",
    quizNotQuite: "Not quite",
    quizNext: "Next question",
    quizSeeScore: "See score",
    quizRetake: "Retake quiz",
    quizComplete: "Quiz complete",
    quizScore: (correct: number, total: number) => `${correct} of ${total} correct`,
    optionLabel: (letter: string, text: string) => `Option ${letter}: ${text}`,
  },

  offline: {
    banner: "You are offline. Showing saved content.",
    stale: "Saved content. It may be out of date.",
  },

  ydc: {
    eyebrow: "YDC",
    title: "Youth Development Center",
    detail: "Grade path and practice on ReferTRM.com. Opens in your browser.",
  },

  home: {
    fig: "Fig 01 / Today",
    employers: "Employers",
    addName: "Add your name",
    greetMorning: "Good morning.",
    greetAfternoon: "Good afternoon.",
    greetEvening: "Good evening.",
    roleLabel: "01 / A REAL ROLE, RIGHT NOW",
    seeAllJobs: "See all jobs",
    noFee: "applying is free, the employer pays",
    openRoles: (n: number) => `${n} open`,
    visitHint: "new role each visit",
    salaryShown: "SALARY SHOWN",
    learnLabel: "02 / LEARN",
    learnTitle: "Build what comes next.",
    learnLessons: (n: number) => `${n} lessons`,
    gameLabel: "03 / CAREER GAME",
    gameTitle: "Decide under pressure.",
    gameDetail: "Real workplace dilemmas.",
    gameHud: "01 of 10 · demo",
    ydcLabel: "04",
    ydcTitle: "Youth Development Center",
    ydcDetail: "Young learners start here too.",
    doorsLabel: "More of your journey · opens in your browser",
    mayaLabel: "05 / ASK MAYA",
    mayaTitle: "An advisor, not an answer.",
    trinityLabel: "06 / TRINITY",
    trinityTitle: "How you decide.",
    trinityFree: "Free",
    trinityPremium: "Premium",
    trinityPro: "Pro",
    cvLabel: "07 / CV & PROFILE",
    cvTitle: "One CV, kept current.",
    referLabel: "08 / REFERRALS",
    referTitle: "Share a role you trust.",
    provenance:
      "Platform: ReferTRM · company of record: Talent Resources Myanmar Co., Ltd. · Licence No. 211/2024",
    heroJob: {
      label: "01 / A REAL ROLE, RIGHT NOW",
      empty: "No public roles are listed right now.",
      error: "Roles could not load on this connection.",
      slow: "Still loading roles. See all jobs below.",
      offline: "Waiting for a connection. Your saved roles are in Jobs.",
      retry: "Try again",
    },
  },

  errors: {
    generic: "Something went wrong. Try again.",
    notFound: "Not found.",
    network: "ReferTRM cannot connect on this network.",
    timeout: "ReferTRM is taking longer than expected.",
    transport: "ReferTRM cannot connect on this network.",
    loading: "Loading…",
    connecting: "Connecting…",
    retry: "Try again",
  },
} as const;

export type Copy = typeof copy;
